server:
  port: 9201

spring:
  application:
    name: gateway
  cloud:
    nacos:
      discovery:
        server-addr: 115.29.150.104:8848

    gateway:
      # 设置与服务注册发现组件结合，这样可以采用服务名的路由策略
      discovery:
        locator:
          enabled: true
        # 配置路由规则
      routes:
        # 采用自定义路由 ID 没什么要求 建议服务名加下标
        - id: client-01
          # 采用 LoadBalanceClient 方式请求，以 lb:// 开头，后面的是注册在 Nacos 上的服务名 lb：默认开启负载算法
          uri: lb://client-01
          #路由优先级
          orser: 1
          # “断言”，主要作用是匹配用户的请求，有很多种用法
          predicates:
            # Method 方法谓词，这里是匹配 GET 请求
            #- Method=GET
            # 请求必须以 study-consumer 打头才会走这个路由
            - Path=/client-01/**
          # 过滤器
          filters:
            #路径转发时向上去除一级
            - StripPrefix=1
